# Generated by Django 2.0.3 on 2018-03-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('b_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('d_date', models.DateField(blank=True, null=True, verbose_name='Date de mort')),
            ],
            options={
                'verbose_name': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers')),
            ],
            options={
                'verbose_name': 'Couverture',
            },
        ),
        migrations.CreateModel(
            name='CoverAutor',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('b_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('d_date', models.DateField(blank=True, null=True, verbose_name='Date de mort')),
            ],
            options={
                'verbose_name': 'Auteur de couverture',
                'verbose_name_plural': 'Auteurs de couverture',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('b_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('parent_genres', models.ManyToManyField(blank=True, to='playel.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('file_ogg', models.FileField(blank=True, upload_to='tracks/mp3', verbose_name='Fichier OGG')),
                ('file_mp3', models.FileField(blank=True, upload_to='tracks/ogg', verbose_name='Fichier MP3')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée')),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('plays_nb', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de lectures')),
                ('autors', models.ManyToManyField(blank=True, to='playel.Autor', verbose_name='Auteurs')),
                ('aux_covers', models.ManyToManyField(blank=True, related_name='_track_aux_covers_+', to='playel.Cover', verbose_name='Couvertures auxilliaires')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Cover', verbose_name='Couverture')),
                ('genres', models.ManyToManyField(blank=True, to='playel.Genre')),
                ('inh_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Album', verbose_name="Hériter des attributs de l'album")),
            ],
            options={
                'verbose_name': 'Piste',
            },
        ),
        migrations.CreateModel(
            name='TrackAlbumRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_nb', models.PositiveSmallIntegerField(default=1, verbose_name='Numéro de piste')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playel.Album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playel.Track', verbose_name='Piste')),
            ],
            options={
                'verbose_name': 'Relation piste-album',
                'verbose_name_plural': 'Relations pistes-albums',
                'ordering': ['track_nb'],
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='cover_autors',
            field=models.ManyToManyField(blank=True, to='playel.CoverAutor', verbose_name='Auteurs de couverture'),
        ),
        migrations.AddField(
            model_name='album',
            name='autors',
            field=models.ManyToManyField(blank=True, to='playel.Autor', verbose_name='Auteurs'),
        ),
        migrations.AddField(
            model_name='album',
            name='aux_covers',
            field=models.ManyToManyField(blank=True, related_name='_album_aux_covers_+', to='playel.Cover', verbose_name='Couvertures auxilliaires'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Cover', verbose_name='Couverture'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, to='playel.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='playel.TrackAlbumRelation', to='playel.Track', verbose_name='Pistes'),
        ),
    ]
