# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playel', '0013_auto_20160829_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='album',
            name='autors',
            field=models.ManyToManyField(blank=True, to='playel.Autor', verbose_name='Auteurs'),
        ),
        migrations.AlterField(
            model_name='album',
            name='aux_covers',
            field=models.ManyToManyField(blank=True, related_name='_album_aux_covers_+', to='playel.Cover', verbose_name='Couvertures auxilliaires'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Cover', verbose_name='Couverture'),
        ),
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='playel.TrackAlbumRelation', to='playel.Track', verbose_name='Pistes'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='b_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='d_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mort'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover_autors',
            field=models.ManyToManyField(blank=True, to='playel.CoverAutor', verbose_name='Auteurs de couverture'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='b_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='d_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mort'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='coverautor',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='b_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='track',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='track',
            name='autors',
            field=models.ManyToManyField(blank=True, to='playel.Autor', verbose_name='Auteurs'),
        ),
        migrations.AlterField(
            model_name='track',
            name='aux_covers',
            field=models.ManyToManyField(blank=True, related_name='_track_aux_covers_+', to='playel.Cover', verbose_name='Couvertures auxilliaires'),
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BPM'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Cover', verbose_name='Couverture'),
        ),
        migrations.AlterField(
            model_name='track',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_mp3',
            field=models.FileField(blank=True, upload_to='tracks/ogg', verbose_name='Fichier MP3'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_ogg',
            field=models.FileField(blank=True, upload_to='tracks/mp3', verbose_name='Fichier OGG'),
        ),
        migrations.AlterField(
            model_name='track',
            name='inh_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playel.Album', verbose_name="Hériter des attributs de l'album"),
        ),
        migrations.AlterField(
            model_name='track',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='track',
            name='plays_nb',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de lectures'),
        ),
        migrations.AlterField(
            model_name='track',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='trackalbumrelation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playel.Track', verbose_name='Piste'),
        ),
        migrations.AlterField(
            model_name='trackalbumrelation',
            name='track_nb',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Numéro de piste'),
        ),
    ]
