# Generated by Django 2.2.2 on 2019-08-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='identifiant')),
                ('pic', models.ImageField(upload_to='', verbose_name='logo')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('quote', models.TextField(blank=True, default='', verbose_name='citation')),
                ('index', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'artiste',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='ajouté')),
                ('url', models.CharField(max_length=128, verbose_name='titre')),
                ('pin', models.BooleanField(default=False, verbose_name='épinglé')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikrave.Artist', verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'oeuvre',
                'ordering': ['-added'],
            },
        ),
    ]
