# Generated by Django 2.2.2 on 2019-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikrave', '0002_auto_20190804_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.CharField(max_length=128, verbose_name='URL'),
        ),
    ]
