# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='generatedPages',
            field=models.IntegerField(verbose_name='Total des pages générées'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='generatedSequences',
            field=models.IntegerField(verbose_name='Total des séquences générées'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='generationTime',
            field=models.DurationField(verbose_name='Total des temps de génération'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date du dernier like'),
        ),
        migrations.AlterField(
            model_name='word',
            name='likes',
            field=models.IntegerField(verbose_name='Nombre de likes'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=32, verbose_name='Mot'),
        ),
    ]
