# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perso', '0002_auto_20170622_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='ajouté')),
                ('pseudo', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField(verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'commentaire',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('image', models.ImageField(upload_to='')),
                ('descr', models.TextField(blank=True, verbose_name='description')),
                ('pin', models.BooleanField(default=False, verbose_name='épinglé')),
            ],
            options={
                'verbose_name': 'couverture',
            },
        ),
        migrations.RemoveField(
            model_name='publication',
            name='categs',
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='résumé'),
        ),
        migrations.AddField(
            model_name='publication',
            name='categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perso.Category', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='épinglé'),
        ),
        migrations.AddField(
            model_name='publication',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='perso.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='comment',
            name='publi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perso.Publication', verbose_name='publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='cover',
            field=models.ManyToManyField(blank=True, to='perso.Cover', verbose_name='couverture'),
        ),
    ]
