# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perso', '0003_auto_20170704_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['added'], 'verbose_name': 'commentaire'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['added'], 'verbose_name': 'publication'},
        ),
    ]
