# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perso', '0006_cover_blackoverlay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='cover',
        ),
        migrations.AddField(
            model_name='publication',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perso.Cover', verbose_name='couverture'),
        ),
    ]
