# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perso', '0007_auto_20170706_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added'], 'verbose_name': 'commentaire'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-added'], 'verbose_name': 'publication'},
        ),
    ]
