# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perso', '0008_auto_20170706_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='ajouté')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'souscription',
            },
        ),
    ]
