app = "syntheses-app"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"
  DEBUG = "1"
  LOG_LEVEL = "WARNING"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
