# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0005_auto_20161017_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['semester', 'subject', 'teacher'], 'verbose_name': 'module'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['slug'], 'verbose_name': 'enseignant'},
        ),
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=32, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profs.Module', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validé'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016, verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='module',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='module',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs.Semester', verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs.Subject', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='module',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs.Teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=16, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='short',
            field=models.CharField(max_length=4, verbose_name='nom abrégé'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short',
            field=models.CharField(max_length=16, verbose_name='nom abrégé'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short',
            field=models.CharField(max_length=16, verbose_name='nom abrégé'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterIndexTogether(
            name='module',
            index_together=set([('semester', 'subject', 'teacher')]),
        ),
    ]
