# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0008_auto_20170622_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
