# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='création')),
                ('last_used', models.DateField(auto_now=True, verbose_name='dernière utilisation')),
                ('times_used', models.IntegerField(default=0, verbose_name="nombre d'utilisations")),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='nom')),
                ('shadowMode', models.BooleanField(default=False, verbose_name='mode discret')),
            ],
            options={
                'verbose_name': 'image dynamique',
                'verbose_name_plural': 'images dynamiques',
            },
        ),
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='création')),
                ('last_used', models.DateField(auto_now=True, verbose_name='dernière utilisation')),
                ('times_used', models.IntegerField(default=0, verbose_name="nombre d'utilisations")),
                ('dwnlTime', models.DurationField(default=datetime.timedelta(0), verbose_name='temps de téléchargement')),
                ('url', models.URLField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': "URL d'image",
                'verbose_name_plural': "URLs d'images",
            },
        ),
        migrations.AddField(
            model_name='dynamicimg',
            name='urls',
            field=models.ManyToManyField(to='dynimg.ImageUrl', verbose_name='URLs'),
        ),
    ]
