# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynimg', '0007_auto_20160812_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicimg',
            name='shadowMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageurl',
            name='dwnlTime',
            field=models.DurationField(blank=True, null=True, verbose_name='Average download time'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='displayedImgs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='processingTime',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='registeredImgs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='registeredUrls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
