# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('modif', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_rank', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
