# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Member')),
            ],
            bases=('register.member',),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='active_disc',
            field=models.BooleanField(default=False),
        ),
    ]
