# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_rank', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activationcode',
            name='active_disc',
            field=models.BooleanField(default=False),
        ),
    ]
