# Generated by Django 2.0.3 on 2018-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-pin', '-added'], 'verbose_name': 'oeuvre'},
        ),
        migrations.AddField(
            model_name='work',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='épinglé'),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identifiant'),
        ),
    ]
