# Generated by Django 2.2.5 on 2019-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180405_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-pin', '-added'], 'verbose_name': 'réalisation'},
        ),
        migrations.AddField(
            model_name='work',
            name='_palette',
            field=models.CharField(blank=True, max_length=20, verbose_name='palette'),
        ),
    ]
