# Generated by Django 2.2.5 on 2019-12-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20191201_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cover_h',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='hauteur couverture'),
        ),
        migrations.AddField(
            model_name='work',
            name='cover_w',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='largeur couverture'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover',
            field=models.ImageField(height_field='cover_h', upload_to='', verbose_name='couverture', width_field='cover_w'),
        ),
    ]
