# Generated by Django 2.2.5 on 2019-12-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20191202_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='hauteur couverture'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_w',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='largeur couverture'),
        ),
    ]
