# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texte')),
                ('author', models.CharField(default='Anonyme', max_length=64, verbose_name='auteur')),
                ('year', models.PositiveSmallIntegerField(default=2016, verbose_name='année')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
            options={
                'verbose_name': 'citation',
            },
        ),
    ]
